const NUMBER_OF_CATEGORIES = 2;

export const NUMBER_OF_TOTAL_DATA_ITEMS = 240;
export const NUMBER_OF_ONE_CATEGORY_QUESTIONS = NUMBER_OF_TOTAL_DATA_ITEMS / NUMBER_OF_CATEGORIES;
export const NUMBER_OF_QUIZ_QUESTIONS = 10;

export const DEFAULT_TIME_TO_ANSWER = 20;
export const MIN_TIME_TO_ANSWER = 5;
export const MAX_TIME_TO_ANSWER = 30;
export const DEFAULT_AUDIO_VOLUME_IN_PERCENTS = 50;

export const NUMBER_OF_CORRECT_ANSWERS_TO_PASSED_QUIZ = 5;
